### ISSUE TITLE
Clarify cause of error in webhook creation failure pages

### ISSUE THREAD

**Issue by BURG3R5** [BURG3R5/github-slack-bot#139]
- [x] Expand `WebhookCreationError`
- [ ] Expand `AuthenticationError`

**Comment by Ayush0Chaudhary** [comment]
mp do it by tomorrow eod

**Comment by Ayush0Chaudhary** [comment]
@BURG3R5 I was not able to find error responses for authentication
closest thing i found is below
https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow
but error codes are not specified here
