### ISSUE TITLE
Investigate failing events.

### ISSUE THREAD

**Issue by BURG3R5** [BURG3R5/github-slack-bot#143]
`review` events correspond to the GitHub webhook event of `pull_request_review.submitted`. Recently these events have been giving a `500` response to GitHub upon delivery. The problem is probably with the `cast_payload_to_event` method of `ReviewEventParser`

**Comment by BURG3R5** [comment]
What's weirder is that Sentry shows no sign of this internal error

**Comment by BURG3R5** [comment]
Worse still, even `issue_opened` events are failing. This means that GitHub has changed something that's common to both of these.

**Comment by Ayush0Chaudhary** [comment]
{
  "action": "submitted",
  "review": {
    "id": 1218998599,
    "node_id": "PRR_kwDOImN3Lc5IqHFH",
    "user": {
      "login": "panda0k",
      "id": 112987706,
      "node_id": "U_kgDOBrwOOg",
      "avatar_url": "https://avatars.githubusercontent.com/u/112987706?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/panda0k",
      "html_url": "https://github.com/panda0k",
      "followers_url": "https://api.github.com/users/panda0k/followers",
      "following_url": "https://api.github.com/users/panda0k/following{/other_user}",
      "gists_url": "https://api.github.com/users/panda0k/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/panda0k/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/panda0k/subscriptions",
      "organizations_url": "https://api.github.com/users/panda0k/orgs",
      "repos_url": "https://api.github.com/users/panda0k/repos",
      "events_url": "https://api.github.com/users/panda0k/events{/privacy}",
      "received_events_url": "https://api.github.com/users/panda0k/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "tdhjgfg",
    "commit_id": "c41d2993dcc7fb0ba7c95e8a33c9aded84dcf536",
    "submitted_at": "2022-12-15T10:55:18Z",
    "state": "changes_requested",
    "html_url": "https://github.com/Ayush0Chaudhary/Rasputin/pull/2#pullrequestreview-1218998599",
    "pull_request_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2",
    "author_association": "COLLABORATOR",
    "_links": {
      "html": {
        "href": "https://github.com/Ayush0Chaudhary/Rasputin/pull/2#pullrequestreview-1218998599"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2"
      }
    }
  },
  "pull_request": {
    "url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2",
    "id": 1166575502,
    "node_id": "PR_kwDOImN3Lc5FiIeO",
    "html_url": "https://github.com/Ayush0Chaudhary/Rasputin/pull/2",
    "diff_url": "https://github.com/Ayush0Chaudhary/Rasputin/pull/2.diff",
    "patch_url": "https://github.com/Ayush0Chaudhary/Rasputin/pull/2.patch",
    "issue_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/2",
    "number": 2,
    "state": "open",
    "locked": false,
    "title": "Update README.md",
    "user": {
      "login": "Ayush0Chaudhary",
      "id": 95746190,
      "node_id": "U_kgDOBbT4jg",
      "avatar_url": "https://avatars.githubusercontent.com/u/95746190?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ayush0Chaudhary",
      "html_url": "https://github.com/Ayush0Chaudhary",
      "followers_url": "https://api.github.com/users/Ayush0Chaudhary/followers",
      "following_url": "https://api.github.com/users/Ayush0Chaudhary/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ayush0Chaudhary/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ayush0Chaudhary/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ayush0Chaudhary/subscriptions",
      "organizations_url": "https://api.github.com/users/Ayush0Chaudhary/orgs",
      "repos_url": "https://api.github.com/users/Ayush0Chaudhary/repos",
      "events_url": "https://api.github.com/users/Ayush0Chaudhary/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ayush0Chaudhary/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": null,
    "created_at": "2022-12-15T10:38:26Z",
    "updated_at": "2022-12-15T10:55:18Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "a030a6fb3898dceafc2c724e62130978726a10b9",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [

    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2/commits",
    "review_comments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2/comments",
    "review_comment_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/2/comments",
    "statuses_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/statuses/c41d2993dcc7fb0ba7c95e8a33c9aded84dcf536",
    "head": {
      "label": "Ayush0Chaudhary:hgfh",
      "ref": "hgfh",
      "sha": "c41d2993dcc7fb0ba7c95e8a33c9aded84dcf536",
      "user": {
        "login": "Ayush0Chaudhary",
        "id": 95746190,
        "node_id": "U_kgDOBbT4jg",
        "avatar_url": "https://avatars.githubusercontent.com/u/95746190?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Ayush0Chaudhary",
        "html_url": "https://github.com/Ayush0Chaudhary",
        "followers_url": "https://api.github.com/users/Ayush0Chaudhary/followers",
        "following_url": "https://api.github.com/users/Ayush0Chaudhary/following{/other_user}",
        "gists_url": "https://api.github.com/users/Ayush0Chaudhary/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Ayush0Chaudhary/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Ayush0Chaudhary/subscriptions",
        "organizations_url": "https://api.github.com/users/Ayush0Chaudhary/orgs",
        "repos_url": "https://api.github.com/users/Ayush0Chaudhary/repos",
        "events_url": "https://api.github.com/users/Ayush0Chaudhary/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Ayush0Chaudhary/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 576943917,
        "node_id": "R_kgDOImN3LQ",
        "name": "Rasputin",
        "full_name": "Ayush0Chaudhary/Rasputin",
        "private": false,
        "owner": {
          "login": "Ayush0Chaudhary",
          "id": 95746190,
          "node_id": "U_kgDOBbT4jg",
          "avatar_url": "https://avatars.githubusercontent.com/u/95746190?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Ayush0Chaudhary",
          "html_url": "https://github.com/Ayush0Chaudhary",
          "followers_url": "https://api.github.com/users/Ayush0Chaudhary/followers",
          "following_url": "https://api.github.com/users/Ayush0Chaudhary/following{/other_user}",
          "gists_url": "https://api.github.com/users/Ayush0Chaudhary/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Ayush0Chaudhary/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Ayush0Chaudhary/subscriptions",
          "organizations_url": "https://api.github.com/users/Ayush0Chaudhary/orgs",
          "repos_url": "https://api.github.com/users/Ayush0Chaudhary/repos",
          "events_url": "https://api.github.com/users/Ayush0Chaudhary/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Ayush0Chaudhary/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/Ayush0Chaudhary/Rasputin",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin",
        "forks_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/forks",
        "keys_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/teams",
        "hooks_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/hooks",
        "issue_events_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/events",
        "assignees_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/tags",
        "blobs_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/languages",
        "stargazers_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/stargazers",
        "contributors_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/contributors",
        "subscribers_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/subscribers",
        "subscription_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/subscription",
        "commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/merges",
        "archive_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/downloads",
        "issues_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/labels{/name}",
        "releases_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/deployments",
        "created_at": "2022-12-11T13:51:49Z",
        "updated_at": "2022-12-11T15:51:35Z",
        "pushed_at": "2022-12-15T10:38:27Z",
        "git_url": "git://github.com/Ayush0Chaudhary/Rasputin.git",
        "ssh_url": "git@github.com:Ayush0Chaudhary/Rasputin.git",
        "clone_url": "https://github.com/Ayush0Chaudhary/Rasputin.git",
        "svn_url": "https://github.com/Ayush0Chaudhary/Rasputin",
        "homepage": null,
        "size": 25,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 2,
        "watchers": 0,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "Ayush0Chaudhary:main",
      "ref": "main",
      "sha": "b710d027a3763919ca6523a2d5ece4d8211dfa5f",
      "user": {
        "login": "Ayush0Chaudhary",
        "id": 95746190,
        "node_id": "U_kgDOBbT4jg",
        "avatar_url": "https://avatars.githubusercontent.com/u/95746190?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Ayush0Chaudhary",
        "html_url": "https://github.com/Ayush0Chaudhary",
        "followers_url": "https://api.github.com/users/Ayush0Chaudhary/followers",
        "following_url": "https://api.github.com/users/Ayush0Chaudhary/following{/other_user}",
        "gists_url": "https://api.github.com/users/Ayush0Chaudhary/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Ayush0Chaudhary/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Ayush0Chaudhary/subscriptions",
        "organizations_url": "https://api.github.com/users/Ayush0Chaudhary/orgs",
        "repos_url": "https://api.github.com/users/Ayush0Chaudhary/repos",
        "events_url": "https://api.github.com/users/Ayush0Chaudhary/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Ayush0Chaudhary/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 576943917,
        "node_id": "R_kgDOImN3LQ",
        "name": "Rasputin",
        "full_name": "Ayush0Chaudhary/Rasputin",
        "private": false,
        "owner": {
          "login": "Ayush0Chaudhary",
          "id": 95746190,
          "node_id": "U_kgDOBbT4jg",
          "avatar_url": "https://avatars.githubusercontent.com/u/95746190?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Ayush0Chaudhary",
          "html_url": "https://github.com/Ayush0Chaudhary",
          "followers_url": "https://api.github.com/users/Ayush0Chaudhary/followers",
          "following_url": "https://api.github.com/users/Ayush0Chaudhary/following{/other_user}",
          "gists_url": "https://api.github.com/users/Ayush0Chaudhary/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Ayush0Chaudhary/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Ayush0Chaudhary/subscriptions",
          "organizations_url": "https://api.github.com/users/Ayush0Chaudhary/orgs",
          "repos_url": "https://api.github.com/users/Ayush0Chaudhary/repos",
          "events_url": "https://api.github.com/users/Ayush0Chaudhary/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Ayush0Chaudhary/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/Ayush0Chaudhary/Rasputin",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin",
        "forks_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/forks",
        "keys_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/teams",
        "hooks_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/hooks",
        "issue_events_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/events",
        "assignees_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/tags",
        "blobs_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/languages",
        "stargazers_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/stargazers",
        "contributors_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/contributors",
        "subscribers_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/subscribers",
        "subscription_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/subscription",
        "commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/merges",
        "archive_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/downloads",
        "issues_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/labels{/name}",
        "releases_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/deployments",
        "created_at": "2022-12-11T13:51:49Z",
        "updated_at": "2022-12-11T15:51:35Z",
        "pushed_at": "2022-12-15T10:38:27Z",
        "git_url": "git://github.com/Ayush0Chaudhary/Rasputin.git",
        "ssh_url": "git@github.com:Ayush0Chaudhary/Rasputin.git",
        "clone_url": "https://github.com/Ayush0Chaudhary/Rasputin.git",
        "svn_url": "https://github.com/Ayush0Chaudhary/Rasputin",
        "homepage": null,
        "size": 25,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Python",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 2,
        "watchers": 0,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2"
      },
      "html": {
        "href": "https://github.com/Ayush0Chaudhary/Rasputin/pull/2"
      },
      "issue": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/2"
      },
      "comments": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/2/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls/2/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/statuses/c41d2993dcc7fb0ba7c95e8a33c9aded84dcf536"
      }
    },
    "author_association": "OWNER",
    "auto_merge": null,
    "active_lock_reason": null
  },
  "repository": {
    "id": 576943917,
    "node_id": "R_kgDOImN3LQ",
    "name": "Rasputin",
    "full_name": "Ayush0Chaudhary/Rasputin",
    "private": false,
    "owner": {
      "login": "Ayush0Chaudhary",
      "id": 95746190,
      "node_id": "U_kgDOBbT4jg",
      "avatar_url": "https://avatars.githubusercontent.com/u/95746190?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Ayush0Chaudhary",
      "html_url": "https://github.com/Ayush0Chaudhary",
      "followers_url": "https://api.github.com/users/Ayush0Chaudhary/followers",
      "following_url": "https://api.github.com/users/Ayush0Chaudhary/following{/other_user}",
      "gists_url": "https://api.github.com/users/Ayush0Chaudhary/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Ayush0Chaudhary/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Ayush0Chaudhary/subscriptions",
      "organizations_url": "https://api.github.com/users/Ayush0Chaudhary/orgs",
      "repos_url": "https://api.github.com/users/Ayush0Chaudhary/repos",
      "events_url": "https://api.github.com/users/Ayush0Chaudhary/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Ayush0Chaudhary/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Ayush0Chaudhary/Rasputin",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin",
    "forks_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/forks",
    "keys_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/teams",
    "hooks_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/hooks",
    "issue_events_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/events",
    "assignees_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/tags",
    "blobs_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/languages",
    "stargazers_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/stargazers",
    "contributors_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/contributors",
    "subscribers_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/subscribers",
    "subscription_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/subscription",
    "commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/merges",
    "archive_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/downloads",
    "issues_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/labels{/name}",
    "releases_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Ayush0Chaudhary/Rasputin/deployments",
    "created_at": "2022-12-11T13:51:49Z",
    "updated_at": "2022-12-11T15:51:35Z",
    "pushed_at": "2022-12-15T10:38:27Z",
    "git_url": "git://github.com/Ayush0Chaudhary/Rasputin.git",
    "ssh_url": "git@github.com:Ayush0Chaudhary/Rasputin.git",
    "clone_url": "https://github.com/Ayush0Chaudhary/Rasputin.git",
    "svn_url": "https://github.com/Ayush0Chaudhary/Rasputin",
    "homepage": null,
    "size": 25,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "main"
  },
  "sender": {
    "login": "panda0k",
    "id": 112987706,
    "node_id": "U_kgDOBrwOOg",
    "avatar_url": "https://avatars.githubusercontent.com/u/112987706?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/panda0k",
    "html_url": "https://github.com/panda0k",
    "followers_url": "https://api.github.com/users/panda0k/followers",
    "following_url": "https://api.github.com/users/panda0k/following{/other_user}",
    "gists_url": "https://api.github.com/users/panda0k/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/panda0k/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/panda0k/subscriptions",
    "organizations_url": "https://api.github.com/users/panda0k/orgs",
    "repos_url": "https://api.github.com/users/panda0k/repos",
    "events_url": "https://api.github.com/users/panda0k/events{/privacy}",
    "received_events_url": "https://api.github.com/users/panda0k/received_events",
    "type": "User",
    "site_admin": false
  }
}

**Comment by Ayush0Chaudhary** [comment]
I verified the payload of both of the event, code was according to payload only,
According to me problem is not in the `cast_payload_to_event`
[payload.txt](https://github.com/BURG3R5/github-slack-bot/files/10236374/payload.txt)

I am also adding the payload I check the functions on

**Comment by Ayush0Chaudhary** [comment]
they both are working fine now.

**Comment by BURG3R5** [comment]
I've checked the instance running on our server and restarted it. Now it's working fine. Dunno what caused it, but by the end it was throwing a lotta `504 Gateway Timeout` errors.
