### ISSUE TITLE
Store the mapping from Slack user id to GitHub username so that we can replace mention them

### ISSUE THREAD

**Issue by BURG3R5** [BURG3R5/github-slack-bot#155]
- [x] Rename the `SecretStorage` class to `GitHubStorage`
- [x] Add a new model class called `User` which has two `CharField`s: `slack_user_id` and `github_user_name`. Both are unique.
- [x] Add this class to `db.create_tables` call in `GitHubStorage.__init__`
- [x] Write wrapper methods for adding and removing this mapping
- [x] Call the `add_user` method from OAuth flow

**Comment by BURG3R5** [comment]
@Magnesium12 This is your next task. Set a deadline for yourself and comment it here.

**Comment by Magnesium12** [comment]
I will try to make a PR for this by 24 EOD.
