### ISSUE TITLE
Update model classes.

### ISSUE THREAD

**Issue by BURG3R5** [BURG3R5/github-slack-bot#59]
- [ ] ~**Prune**: Do not initialize unnecessary attributes in models, even with `None`.~
- [ ] **Show**: Add descriptive `__str__` methods for debugging and testing purposes.

**Comment by shashank-k-y** [comment]
Hi @BURG3R5 , can you please grant me permission, so i can rise pull request for this issue. its giving permission denied error at my end.

**Comment by BURG3R5** [comment]
@shashank-k-y It's saying permission denied because you're trying to push to this main repo. You forked this repo, right? Try pushing to that repo and then making a PR to this one.

[Helpful link](https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/)

**Comment by shashank-k-y** [comment]
okay @BURG3R5

**Comment by shashank-k-y** [comment]
Hi @BURG3R5 , after noting the points you have mentioned, I have closed the #61 and created new PR #62 . which covers the second issue, please add some more details for the first issue, will try to push changes accordingly.

**Comment by BURG3R5** [comment]
Don't worry, I'll create a separate issue for the first problem in a minute.

**Comment by shashank-k-y** [comment]
> 

sure, Thanks
